version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bbb_dashboard
      - POSTGRES_USER=bbb
      - POSTGRES_PASSWORD=bbb@123